let user1 = {
  "idDB": 1,
  "idAuth0": "1234",
  "email": "asdf",
  "picture": "asdf",
  "name": "asdf",
  "familyName": "new",
  "age": "2023-05-08T13:09:14.771Z",
  "phone": "1234567",
  "location": "cuba",
  "currentLocation": [],
  "readyMove": false,
  "workingHours": "few",
  "workingModal": "hybrid",
  "socialMedia": ["instagram-account"],
  "skillsProf": [],
  "stack": [],
  "compLanguages": [],
  "about": "not much",
  "video": "asdf",
  "languages": [],
  "hobbies": [],
  "salaryRange": 1000,
  "desiredLocation": [],
  "notDesiredLocation": [],
  "desiredWorkingModal": "hybrid"
}

let user2 = {
  "idDB": 2,
  "idAuth0": "5678",
  "email": "asdf@rightone.com",
  "picture": "asdf",
  "name": "Paola",
  "familyName": "new",
  "age": "2023-05-08T13:10:13.989Z",
  "phone": "1234567",
  "location": "cuba",
  "currentLocation": [],
  "readyMove": false,
  "workingHours": "few",
  "workingModal": "hybrid",
  "socialMedia": [
    "instagram-account"
  ],
  "skillsProf": [],
  "stack": [],
  "compLanguages": [],
  "about": "not much",
  "video": "asdf",
  "languages": [],
  "hobbies": [],
  "salaryRange": 1000,
  "desiredLocation": [],
  "notDesiredLocation": [],
  "desiredWorkingModal": "hybrid"
}