export const xavi = {
  idAuth: "98fewfwe3423223746",
  email: "xavier.graells324@ontrack.com",
  picture: "xavier.png",
  name: "Xavier",
  familyName: "Graells",
  age: "1994-01-01T00:00:00.000Z",
  phone: "6578412",
  location: "Barcelona",
  readyMove: true,
  workingHours: "Full-time",
  workingModal: "office",
  socialMedia: ["xavi@instagram.com"],
  skillsProf: ["Analytics", "UI"],
  stack: ["Express", "Cypress"],
  compLanguages: ["Javascript", "React"],
  about: "I'm 28 years old catalan guy from Terrassa",
  video: "",
  languages: ["Spanish - Native", "Catalan - Native", "English - Advanced"],
  hobbies: ["sport"],
  salaryRange: 40000,
  desiredLocation: ["Londres", "Amsterdam"],
  notDesiredLocation: ["Terrassa"],
  desiredWorkingModal: "On-site",
  currentLocation: ["41.1188827", "1.2444909"],
};

export const guillaume = {
  idAuth: "4523264few32fwe45",
  email: "guillaumerouchaud324@ontrack.com",
  picture: "guillaume.png",
  name: "Guillaume",
  familyName: "Rouchaud",
  age: "1993-01-01T00:00:00.000Z",
  phone: "6578412",
  location: "Barcelona",
  readyMove: true,
  workingHours: "Internship",
  workingModal: "Hybrid",
  socialMedia: ["www.facebook.com/guillaume"],
  skillsProf: ["Analytics", "UI"],
  stack: ["Tailwind", "Express"],
  compLanguages: ["Javascript", "Typescript"],
  about: "I'm 29 years old guy from France",
  video: "",
  languages: ["Spanish - Advanced", "Catalan - Beginner", "English - Advanced", "French - Native"],
  hobbies: ["sport"],
  salaryRange: 32000,
  desiredLocation: ["Madrid", "San sebastian"],
  notDesiredLocation: ["Terrassa"],
  desiredWorkingModal: "Hybrid",
  currentLocation: ["41.56314820000001", "2.0054917"],
};

export const paola = {
  idAuth: "32323244eef432wfw1",
  email: "paolapatinobtvfrcdx324@ontrack.com",
  picture: "paola.png",
  name: "Paola",
  familyName: "Patiño",
  age: "1993-01-01T00:00:00.000Z",
  phone: "6578412",
  location: "Badalona",
  readyMove: true,
  workingHours: "Part-time",
  workingModal: "Remote",
  socialMedia: [],
  skillsProf: ["Automation", "Virtualisation"],
  stack: ["Koa", "Cypress", "Jest"],
  compLanguages: ["Angular", "React", "Python"],
  about: "I'm 29 years old girl from Colombia",
  video: "",
  languages: ["Spanish - Native", "English - Advanced"],
  hobbies: ["Guitarra"],
  salaryRange: 35000,
  desiredLocation: ["Bogota", "Amsterdam", "Berlin"],
  notDesiredLocation: ["Badalona"],
  desiredWorkingModal: "Remote",
  currentLocation: ["41.4469883", "2.2450325"],
};
export const rosie = {
  idAuth: "U_kgDOB0L623_A",
  email: "rosiedyvig23@gmail.com",
  picture: "https://avatars.githubusercontent.com/u/121830140?v=4",
  name: "Rosie Dyvig",
  familyName: "MANGOS",
  age: "2023-05-11T00:00:00.000Z",
  phone: "",
  location: "Manresa",
  readyMove: null,
  workingHours: "Part-time",
  workingModal: "Freelance",
  socialMedia: [],
  skillsProf: [],
  stack: [],
  compLanguages: [],
  about: "",
  video: "",
  languages: ["English - Native", "Spanish - Beginner"],
  hobbies: [],
  salaryRange: 0,
  desiredLocation: [],
  notDesiredLocation: [],
  desiredWorkingModal: null,
  currentLocation: ["41.7211121", "1.8164413"],
};

export const maria = {
  idAuth: "U_kgDOBzkY23238g",
  email: "igoninamv232323@yandex.ru",
  picture: "https://avatars.githubusercontent.com/u/121182450?v=4",
  name: "mango",
  familyName: "MANGO",
  age: "2023-05-04T00:00:00.000Z",
  phone: "",
  location: "Saint Petersburg",
  readyMove: true,
  workingHours: "Freelance",
  workingModal: "Flextime",
  socialMedia: [],
  skillsProf: [],
  stack: [],
  compLanguages: [],
  about: "",
  video: "",
  languages: ["Russian - Native", "English - Advanced", "Spanish - Beginner"],
  hobbies: [],
  salaryRange: 0,
  desiredLocation: ["Barcelona", "Sevilla", "Bilbao"],
  notDesiredLocation: [],
  desiredWorkingModal: null,
  currentLocation: ["41.3873974", "2.168568"],
};
