export const xavi = {
  idAuth: "98fewfwe3423223746",
  email: "xavier.graells324@ontrack.com",
  picture: "xavier.png",
  name: "Xavier",
  familyName: "Graells",
  age: "1994-01-01T00:00:00.000Z",
  phone: "6578412",
  location: "barcelona",
  readyMove: true,
  workingHours: "full-time",
  workingModal: "office",
  socialMedia: ["xavi@instagram.com"],
  skillsProf: ["analytics", "UI"],
  stack: ["express", "cypress"],
  compLanguages: ["javascript", "react"],
  about: "I'm 28 years old catalan guy from Terrassa",
  video: "",
  languages: ["spanish3", "catalan3", "english2"],
  hobbies: ["sport"],
  salaryRange: 40000,
  desiredLocation: ["londres", "amsterdam"],
  notDesiredLocation: ["Tarragona"],
  desiredWorkingModal: "office",
  currentLocation: ["41.1188827", "1.2444909"],
};

export const guillaume = {
  idAuth: "4523264few32fwe45",
  email: "guillaumerouchaud324@ontrack.com",
  picture: "guillaume.png",
  name: "Guillaume",
  familyName: "Rouchaud",
  age: "1993-01-01T00:00:00.000Z",
  phone: "6578412",
  location: "barcelona",
  readyMove: true,
  workingHours: "internship",
  workingModal: "hybrid",
  socialMedia: ["www.facebook.com/guillaume"],
  skillsProf: ["analytics", "UI"],
  stack: ["tailwind", "express"],
  compLanguages: ["javascript", "typescript"],
  about: "I'm 29 years old guy from France",
  video: "",
  languages: ["spanish2", "catalan0", "english2", "french3"],
  hobbies: ["sport"],
  salaryRange: 32000,
  desiredLocation: ["madrid", "san sebastian"],
  notDesiredLocation: ["terrassa"],
  desiredWorkingModal: "hybrid",
  currentLocation: ["41.56314820000001", "2.0054917"],
};

export const paola = {
  idAuth: "32323244eef432wfw1",
  email: "paolapatinobtvfrcdx324@ontrack.com",
  picture: "paola.png",
  name: "Paola",
  familyName: "Patiño",
  age: "1993-01-01T00:00:00.000Z",
  phone: "6578412",
  location: "Badalona",
  readyMove: true,
  workingHours: "part-time",
  workingModal: "remote",
  socialMedia: [],
  skillsProf: ["automation", "virtualisation"],
  stack: ["koa", "cypress", "jest"],
  compLanguages: ["angular", "react", "python"],
  about: "I'm 29 years old girl guy from Colombia",
  video: "",
  languages: ["spanish3", "english2"],
  hobbies: ["guitarra"],
  salaryRange: 35000,
  desiredLocation: ["bogota", "amsterdam", "berlin"],
  notDesiredLocation: ["Badalona"],
  desiredWorkingModal: "remote",
  currentLocation: ["41.4469883", "2.2450325"],
};
export const rosie = {
  idAuth: "U_kgDOB0L623_A",
  email: "rosiedyvig23@gmail.com",
  picture: "https://avatars.githubusercontent.com/u/121830140?v=4",
  name: "Rosie Dyvig",
  familyName: "MANGOS",
  age: "2023-05-11T00:00:00.000Z",
  phone: "",
  location: "Manresa",
  readyMove: null,
  workingHours: "",
  workingModal: "",
  socialMedia: [],
  skillsProf: [],
  stack: [],
  compLanguages: [],
  about: "",
  video: "",
  languages: [],
  hobbies: [],
  salaryRange: 0,
  desiredLocation: [],
  notDesiredLocation: [],
  desiredWorkingModal: null,
  currentLocation: ["41.7211121", "1.8164413"],
};

export const maria = {
  idAuth: "U_kgDOBzkY23238g",
  email: "igoninamv232323@yandex.ru",
  picture: "https://avatars.githubusercontent.com/u/121182450?v=4",
  name: "mango",
  familyName: "MANGO",
  age: "2023-05-04T00:00:00.000Z",
  phone: "",
  location: "",
  readyMove: true,
  workingHours: "",
  workingModal: "",
  socialMedia: [],
  skillsProf: [],
  stack: [],
  compLanguages: [],
  about: "",
  video: "",
  languages: [],
  hobbies: [],
  salaryRange: 0,
  desiredLocation: [],
  notDesiredLocation: [],
  desiredWorkingModal: null,
  currentLocation: ["41.3873974", "2.168568"],
};
